apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    app: {{ .Chart.Name }}
    component: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: 3306
      name: mysql-3306
  selector:
    app: {{ .Chart.Name }}
