apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    app: {{ .Chart.Name }}
    component: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port1.port }}
      name: {{ .Values.service.port1.name }}
  selector:
    app: {{ .Chart.Name }}
